export enum AppPhase {
  CollectionDataEmpty = 'collection-data-empty',
  CollectionDataError = 'collection-data-error',
  CollectionDataLoaded = 'collection-data-loaded',
  CollectionError = 'collection-error',
  CollectionsEmpty = 'collections-empty',
  CollectionsLoaded = 'collections-loaded',
  ConnectionsError = 'connections-error',
  ConnectionsLoaded = 'connections-loaded',
  CreatingEnvironment = 'creating-environment',
  CreatingMongoUrl = 'creating-mongo-url',
  CreatingName = 'creating-name',
  CreatingType = 'creating-type',
  DatabaseError = 'database-error',
  DatabasesEmpty = 'databases-empty',
  DatabasesLoaded = 'databases-loaded',
  LoadingCollections = 'loading-collections',
  LoadingCollectionData = 'loading-collection-data',
  LoadingConnections = 'loading-connections',
  LoadingDatabases = 'loading-databases',
  SavingConnection = 'saving-connection',
  UnsupportedConnection = 'unsupported-connection',
}
