export enum AppPhase {
  CollectionDataEmpty = 'collection-data-empty',
  CollectionDataError = 'collection-data-error',
  CollectionDataLoaded = 'collection-data-loaded',
  CollectionError = 'collection-error',
  CollectionsEmpty = 'collections-empty',
  CollectionsLoaded = 'collections-loaded',
  ConnectionsError = 'connections-error',
  ConnectionsLoaded = 'connections-loaded',
  ConfirmingConnectionDeletion = 'confirming-connection-deletion',
  CreatingConnection = 'creating-connection',
  DatabaseError = 'database-error',
  DatabasesEmpty = 'databases-empty',
  DatabasesLoaded = 'databases-loaded',
  DeletingConnection = 'deleting-connection',
  LoadingCollections = 'loading-collections',
  LoadingCollectionData = 'loading-collection-data',
  LoadingConnections = 'loading-connections',
  LoadingDatabases = 'loading-databases',
  SavingConnection = 'saving-connection',
  UnsupportedConnection = 'unsupported-connection',
}
